Implementation;Compile;RootName:m2s010_som
Implementation;Compile||(null)||Please refer to the log file for details about 1 Warning(s) , 8 Info(s)||m2s010_som_compile_log.log;liberoaction://open_report/file/m2s010_som_compile_log.log||(null);(null)
Implementation;Place and Route||OnlineHelp;liberoaction://open_online_help/98369539||Info: I/O Bank and Globals Assigner detected (1) out of (10) I/O Bank(s) with locked I/O technologies.||(null);(null)||(null);(null)
Implementation;Place and Route;RootName:m2s010_som
Implementation;Place and Route||(null)||Please refer to the log file for details about 5 Info(s)||m2s010_som_layout_log.log;liberoaction://open_report/file/m2s010_som_layout_log.log||(null);(null)
Implementation;Generate Bitstream;RootName:m2s010_som
Implementation;Generate Bitstream||(null)||Please refer to the log file for details||m2s010_som_generateBitstream.log;liberoaction://open_report/file/m2s010_som_generateBitstream.log||(null);(null)
HelpInfo,C:\Microsemi\Libero_SoC_v11.8\SynplifyPro\lib\html,fpgahelp.qhc,errormessages.mp,C:\Microsemi\Libero_SoC_v11.8\SynplifyPro\bin\mbin\assistant
